name: Pull Request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-22.04, macos-12, macos-11, windows-2022]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

    - name: Install Dependencies
      run: poetry install --no-interaction

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Vulnerability Scan
      run: make secure

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      run: make build
