name: Pull Request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        py: [3.7, 3.8, 3.9, 3.10, 3.11]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3

    - uses: actions/setup-py@v4
      with:
        python-version: ${{ matrix.py }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install --no-interaction

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      run: make build
