name: Release Tag

on:
  push:
    tags: [ "v*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout branch
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

    - name: Install Dependencies
      run: poetry install --no-interaction

    - name: Build and Publish to Pypi
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}